server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    password: r$d7dBd8d%dkB6Gd8s4s
    url: jdbc:sqlserver://streamingservervideo.database.windows.net:1433;database=VideoUsers;user=matt95@streamingservervideo;password=r$d7dBd8d%dkB6Gd8s4s;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: matt95@streamingservervideo
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        format_sql: true
    show-sql: true
  cloud:
    azure:
      storage:
        blob:
          account-name: videostreamingservice
          account-key: sp=racwdli&st=2022-11-22T09:28:36Z&se=2023-02-28T17:28:36Z&sv=2021-06-08&sr=c&sig=%2B7a5ODIdFI9pjYpKrdMVY2S7Q9u9Jx2j8qWoAOe5cfo%3D
          endpoint: https://videostreamingservice.blob.core.windows.net
      cosmos:
        endpoint: https://clouddevproject.documents.azure.com:443/
        key: WkOfmR00q6vRfZzM2J7l8YiClUeOcSePg7HcqjTDUEvjeexYp4VcXpBKBdknzouWNtDRwGAwCHBQACDbkfarXQ==
        database: videostreaming
        populate-query-metrics: true
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

