server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    password: saxophone100
    url: jdbc:postgresql://localhost:5432/registration
    username: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  cloud:
    azure:
      storage:
        blob:
          account-name: videostreamingservice
          account-key: LS0losB4f73o4U6Xw47a3aQcAxUqf5eE40kOG/56VStVteneZxMmyfgsQxRW6CBwSujHSR3+VSgo+AStJ7R+tA==
          endpoint: https://videostreamingservice.blob.core.windows.net
      cosmos:
        endpoint: https://clouddevproject.documents.azure.com:443/
        key: WkOfmR00q6vRfZzM2J7l8YiClUeOcSePg7HcqjTDUEvjeexYp4VcXpBKBdknzouWNtDRwGAwCHBQACDbkfarXQ==
        database: videostreaming
        populate-query-metrics: true
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

