name: Create a Docker image to place it on Azure Container repo
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: azure/docker-login@v1
        with:
          login-server: containerstuff.azurecr.io
          username: containerstuff
          password: BzvAjWq4zqwhl3Vi9ADD5dzEqwcvdaGCTQf80bPyRp+ACRB6nOtS
      - run: |
          docker build . -t containerstuff.azurecr.io/deployments:${{ github.sha }}
          docker push containerstuff.azurecr.io/deployments:${{ github.sha }}