name: Create a Docker image to place it on Azure Container repo
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: azure/docker-login@v1
        with:
          login-server: videostreamingcontainer.azurecr.io
          username: videostreamingcontainer
          password: sINi8//Qg2so3LkV6esYYYbqjTs9kXsl
      - run: |
          docker build . -t videostreamingcontainer.azurecr.io/mattdev95:${{ github.sha }}
          docker push videostreamingcontainer.azurecr.io/mattdev95:${{ github.sha }}