name: Create a Docker image to place it on Azure Container repo
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: azure/docker-login@v1
        with:
          login-server: streamingcontainer.azurecr.io
          username: streamingcontainer
          password: vZ8H8el2BveV1ByFm54048uHy+Vko+UmOInEl3Wb5Y+ACRC6L0Ky
      - run: |
          docker build . -t streamingcontainer.azurecr.io/mattdev95:${{ github.sha }}
          docker push streamingcontainer.azurecr.io/mattdev95:${{ github.sha }}